In [3]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

import pandas as pd

# 엑셀 파일 불러오기 (로컬 경로)
file_path = r'C:\Users\Administrator\dataset\Raisin.xlsx'
df = pd.read_excel(file_path)

# 데이터 확인
print(df.head())


    Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0  87524       442.246011       253.291155      0.819738       90546   
1  75166       406.690687       243.032436      0.801805       78789   
2  90856       442.267048       266.328318      0.798354       93717   
3  45928       286.540559       208.760042      0.684989       47336   
4  79408       352.190770       290.827533      0.564011       81463   

     Extent  Perimeter    Class  
0  0.758651   1184.040  Kecimen  
1  0.684130   1121.786  Kecimen  
2  0.637613   1208.575  Kecimen  
3  0.699599    844.162  Kecimen  
4  0.792772   1073.251  Kecimen  


In [6]:
# 'Class' 열 삭제
df = df.drop('Class', axis=1)
df

Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0    87524       442.246011       253.291155      0.819738       90546   
1    75166       406.690687       243.032436      0.801805       78789   
2    90856       442.267048       266.328318      0.798354       93717   
3    45928       286.540559       208.760042      0.684989       47336   
4    79408       352.190770       290.827533      0.564011       81463   
..     ...              ...              ...           ...         ...   
895  83248       430.077308       247.838695      0.817263       85839   
896  87350       440.735698       259.293149      0.808629       90899   
897  99657       431.706981       298.837323      0.721684      106264   
898  93523       476.344094       254.176054      0.845739       97653   
899  85609       512.081774       215.271976      0.907345       89197   

       Extent  Perimeter  
0    0.758651   1184.040  
1    0.684130   1121.786  
2    0.637613   1208.575  
3    0.699599    844.162  
4    0.792772   1073.251  
..        ...        ...  
895  0.668793   1129.072  
896  0.636476   1214.252  
897  0.741099   1292.828  
898  0.658798   1258.548  
899  0.632020   1272.862  

[900 rows x 7 columns]

In [7]:
# 컬렴명 확인
df.columns

Index(['Area', 'MajorAxisLength', 'MinorAxisLength', 'Eccentricity',
       'ConvexArea', 'Extent', 'Perimeter'],
      dtype='object')

In [8]:
# 결측치 제거
df = df.dropna()
df.isnull().sum()

Area               0
MajorAxisLength    0
MinorAxisLength    0
Eccentricity       0
ConvexArea         0
Extent             0
Perimeter          0
dtype: int64

In [10]:
X=df.drop('Perimeter',axis=1)
X.head()

Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea    Extent
0  87524       442.246011       253.291155      0.819738       90546  0.758651
1  75166       406.690687       243.032436      0.801805       78789  0.684130
2  90856       442.267048       266.328318      0.798354       93717  0.637613
3  45928       286.540559       208.760042      0.684989       47336  0.699599
4  79408       352.190770       290.827533      0.564011       81463  0.792772

In [11]:
y=df['Perimeter']
y.value_counts()

1184.040    1
1394.100    1
1388.684    1
1502.661    1
1219.105    1
           ..
1103.153    1
970.754     1
989.499     1
1018.553    1
1272.862    1
Name: Perimeter, Length: 900, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [15]:
from sklearn.svm import SVC

# 만약 레이블이 연속형이라면, 적절히 범주형으로 변환해야 합니다.
# 예를 들어, 연속형 값에서 임계값을 기준으로 이진 분류로 변환할 수 있습니다.
# 아래는 임계값을 기준으로 0과 1로 변환하는 예시입니다.

# 임의의 임계값을 기준으로 범주형으로 변환 (예: 중간값을 기준으로 변환)
threshold = y_train.median()
y_train_categorical = (y_train > threshold).astype(int)
y_test_categorical = (y_test > threshold).astype(int)

# SVM 모델 학습 및 평가
clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train_categorical)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test_categorical, pred_svm))
print(confusion_matrix(y_test_categorical, pred_svm))


505    1331.797
210     869.795
655    1027.513
50      845.786
674    1100.929
Name: Perimeter, dtype: float64
492    1269.066
141     938.705
409    1254.861
31      828.697
570    1345.426
Name: Perimeter, dtype: float64

--- SVM Classifier ---
0.9288888888888889
[[104   4]
 [ 12 105]]


In [18]:
# Build a logistic regression classifier and predict

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# 임의의 임계값을 기준으로 범주형으로 변환 (예: 중간값을 기준으로 변환)
threshold = y_train.median()
y_train_categorical = (y_train > threshold).astype(int)
y_test_categorical = (y_test > threshold).astype(int)

# 로지스틱 회귀 모델 학습 및 예측
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train_categorical)

pred_lr = clf_lr.predict(X_test)

# 결과 출력
print("\n--- Logistic Regression Classifier ---")
print(accuracy_score(y_test_categorical, pred_lr))
print(confusion_matrix(y_test_categorical, pred_lr))


--- Logistic Regression Classifier ---
0.9688888888888889
[[107   1]
 [  6 111]]


In [20]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# y_train과 y_test 모두 범주형(이진) 데이터로 변환
threshold = y_train.median()
y_train_categorical = (y_train > threshold).astype(int)
y_test_categorical = (y_test > threshold).astype(int)

# 신경망 분류기(Neural Network Classifier) 학습
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(X_train, y_train_categorical)

# 예측
pred_nn = clf_nn.predict(X_test)

# 정확도 및 혼동 행렬 출력
print("\n--- Neural Network Classifier ---")
print(accuracy_score(y_test_categorical, pred_nn))
print(confusion_matrix(y_test_categorical, pred_nn))



--- Neural Network Classifier ---
0.5244444444444445
[[  1 107]
 [  0 117]]


In [22]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

# 모델 생성 및 훈련
clf_dt = DecisionTreeRegressor(random_state=0)
clf_dt.fit(X_train, y_train)

# 예측
pred_dt = clf_dt.predict(X_test)

# 결과 출력
print("\n--- Decision Tree Regressor ---")
print("Mean Squared Error:", mean_squared_error(y_test, pred_dt))
print("R^2 Score:", r2_score(y_test, pred_dt))



--- Decision Tree Regressor ---
Mean Squared Error: 1796.595228017778
R^2 Score: 0.9781484429885012


In [26]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print("\n--- Random Forest Regressor ---")
rf_reg = RandomForestRegressor(random_state=0)
rf_reg.fit(X_train, y_train)
pred = rf_reg.predict(X_test)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R^2 Score:", r2_score(y_test, pred))


--- Random Forest Regressor ---
Mean Squared Error: 1510.9524709763175
R^2 Score: 0.9816226473574508
